name: ZAP Scan CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Subir DVWA
        run: |
          docker run -d --name dvwa -p 8080:80 vulnerables/web-dvwa
          sleep 15

      - name: Rodar OWASP ZAP
        run: |
          docker run -t --network="host" \
            -v $(pwd):/zap/wrk/:rw \
            ghcr.io/zaproxy/zaproxy:stable zap-full-scan.py \
              -t http://localhost:8080 \
              -r /zap/wrk/relatorio-zap.html \
              -I

      - name: Upload do relatório
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: relatorio-zap.html
