name: ZAP Scan CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Criar rede para ZAP + DVWA
        run: docker network create zapnet

      - name: Subir DVWA
        run: |
          docker run -d --name dvwa --network zapnet vulnerables/web-dvwa
          # dá um tempo pro container subir
          sleep 20

      - name: Rodar OWASP ZAP (full scan)
        run: |
          docker run -t --network zapnet \
            -v $(pwd):/zap/wrk/:rw \
            ghcr.io/zaproxy/zaproxy:stable zap-full-scan.py \
              -t http://dvwa \
              -r /zap/wrk/relatorio-zap.html \
              -I

      - name: Upload do relatório
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: relatorio-zap.html
